import { Bell, CreditCard, FileText, Home, User } from "lucide-react";
import type {
  AppNotification,
  Citizen,
  Invoice,
  NavItem,
  PageMeta,
  Payment,
  TabKey,
} from "./types";

/* This structure intentionally follows the Citizen Laravel model. */
export const CURRENT_CITIZEN: Citizen = {
  id: "019ff57f-8d00-7361-a5ce-1f6ec1d729dd",
  citizen_uid: "CTZ-2026-000124",
  full_name: "Tigist Girma",
  phone: "+251 91 234 5678",
  national_id: "ET-123456789",
  address: "Adama, Kebele 03",
  gender: "FEMALE",
  date_of_birth: "1998-04-15",
  administrative_unit: { id: "au-07", name: "Adama City", type: "CITY" },
  registered_sector: { id: "sector-03", name: "Revenue Sector" },
  registered_at: "2026-01-10",
  source: "SYSTEM",
  external_id: null,
  is_active: true,
};

export const PAYMENTS: Payment[] = [
  {
    id: "pay-001",
    transaction_number: "TXN-88921",
    title: "Business License",
    method: "Telebirr",
    amount: 5000,
    status: "SUCCESS",
    paid_at: "2026-08-12 10:30",
  },
  {
    id: "pay-002",
    transaction_number: "TXN-81004",
    title: "Property Service Fee",
    method: "CBE Birr",
    amount: 1800,
    status: "SUCCESS",
    paid_at: "2026-07-28 14:20",
  },
  {
    id: "pay-003",
    transaction_number: "TXN-77410",
    title: "Land Tax",
    method: "Telebirr",
    amount: 10000,
    status: "FAILED",
    paid_at: "2026-08-10 09:15",
  },
];

export const NOTIFICATIONS: AppNotification[] = [
  {
    id: "notification-001",
    title: "Land Tax invoice is awaiting payment",
    message: "Invoice INV-2026-0001 is currently unpaid.",
    time: "Today · 8:02 AM",
    kind: "WARNING",
    unread: true,
  },
  {
    id: "notification-002",
    title: "Payment confirmed",
    message: "Your Business License payment was successfully completed.",
    time: "Yesterday · 4:41 PM",
    kind: "SUCCESS",
    unread: false,
  },
  {
    id: "notification-003",
    title: "Payment attempt failed",
    message: "Your Land Tax payment attempt was unsuccessful.",
    time: "Aug 10 · 11:15 AM",
    kind: "WARNING",
    unread: false,
  },
  {
    id: "notification-004",
    title: "Citizen profile verified",
    message: "Your citizen information has been successfully verified.",
    time: "Aug 08 · 9:30 AM",
    kind: "INFO",
    unread: false,
  },
];

export const NAV_ITEMS: NavItem[] = [
  { key: "home", label: "Home", short: "Home", icon: Home },
  { key: "invoices", label: "Invoices", short: "Invoices", icon: FileText },
  { key: "payments", label: "Payments", short: "Payments", icon: CreditCard },
  { key: "notifications", label: "Notifications", short: "Alerts", icon: Bell },
  { key: "profile", label: "Profile", short: "Me", icon: User },
];

export const PAGE_META: Record<TabKey, PageMeta> = {
  home: { title: "Home", sub: "Overview of your services and payments" },
  invoices: { title: "Invoices", sub: "Galii Murtessaa · assessed dues" },
  payments: { title: "Payments", sub: "Galii Sassaabaa · transaction record" },
  notifications: { title: "Notifications", sub: "Beeksisaalee · account activity" },
  profile: { title: "Profile", sub: "Odeeffannoo dhuunfaa · citizen record" },
};


export const INVOICES: Invoice[] = [
  {
    id: "inv-001",
    invoice_number: "INV-2026-0001",
    assessment: {
      id: "asm-001",
      assessment_number: "ASM-2026-000041",
      assessment_date: "2026-06-28",
    },
    status: "OVERDUE",
    currency: "ETB",
    subtotal: 10800,
    discount_amount: 0,
    penalty_amount: 500,
    total_amount: 11300,
    paid_amount: 0,
    balance_due: 11300,
    issued_at: "2026-07-01",
    due_date: "2026-08-15",
    paid_at: null,
    items: [
      {
        id: "item-001-1",
        invoice_id: "inv-001",
        line_number: 1,
        description: "Land Tax 2026",
        quantity: 500,
        unit: "M2",
        unit_price: 18,
        amount: 9000,
        discount_amount: 0,
        penalty_amount: 500,
        total_amount: 9500,
        currency: "ETB",
      },
      {
        id: "item-001-2",
        invoice_id: "inv-001",
        line_number: 2,
        description: "Waste Collection Fee",
        quantity: null,
        unit: null,
        unit_price: null,
        amount: 1000,
        discount_amount: 0,
        penalty_amount: 0,
        total_amount: 1000,
        currency: "ETB",
      },
      {
        id: "item-001-3",
        invoice_id: "inv-001",
        line_number: 3,
        description: "Fire Safety Inspection Fee",
        quantity: null,
        unit: null,
        unit_price: null,
        amount: 800,
        discount_amount: 0,
        penalty_amount: 0,
        total_amount: 800,
        currency: "ETB",
      },
    ],
  },
  {
    id: "inv-002",
    invoice_number: "INV-2026-0002",
    assessment: {
      id: "asm-002",
      assessment_number: "ASM-2026-000038",
      assessment_date: "2026-06-15",
    },
    status: "PAID",
    currency: "ETB",
    subtotal: 5000,
    discount_amount: 0,
    penalty_amount: 0,
    total_amount: 5000,
    paid_amount: 5000,
    balance_due: 0,
    issued_at: "2026-06-20",
    due_date: "2026-06-30",
    paid_at: "2026-06-25",
    items: [
      {
        id: "item-002-1",
        invoice_id: "inv-002",
        line_number: 1,
        description: "Business License Renewal",
        quantity: null,
        unit: null,
        unit_price: null,
        amount: 5000,
        discount_amount: 0,
        penalty_amount: 0,
        total_amount: 5000,
        currency: "ETB",
      },
    ],
  },
  {
    id: "inv-003",
    invoice_number: "INV-2026-0003",
    assessment: {
      id: "asm-003",
      assessment_number: "ASM-2026-000052",
      assessment_date: "2026-07-29",
    },
    status: "PARTIALLY_PAID",
    currency: "ETB",
    subtotal: 2400,
    discount_amount: 200,
    penalty_amount: 0,
    total_amount: 2200,
    paid_amount: 1000,
    balance_due: 1200,
    issued_at: "2026-08-01",
    due_date: "2026-08-30",
    paid_at: null,
    items: [
      {
        id: "item-003-1",
        invoice_id: "inv-003",
        line_number: 1,
        description: "Vehicle Tax — Isuzu FSR",
        quantity: 1,
        unit: "VEHICLE",
        unit_price: 2400,
        amount: 2400,
        discount_amount: 200,
        penalty_amount: 0,
        total_amount: 2200,
        currency: "ETB",
      },
    ],
  },
  {
    id: "inv-004",
    invoice_number: "INV-2026-0004",
    assessment: {
      id: "asm-004",
      assessment_number: "ASM-2026-000029",
      assessment_date: "2026-05-08",
    },
    status: "PAID",
    currency: "ETB",
    subtotal: 1800,
    discount_amount: 0,
    penalty_amount: 0,
    total_amount: 1800,
    paid_amount: 1800,
    balance_due: 0,
    issued_at: "2026-05-10",
    due_date: "2026-05-30",
    paid_at: "2026-05-22",
    items: [
      {
        id: "item-004-1",
        invoice_id: "inv-004",
        line_number: 1,
        description: "Property Service Fee",
        quantity: null,
        unit: null,
        unit_price: null,
        amount: 1300,
        discount_amount: 0,
        penalty_amount: 0,
        total_amount: 1300,
        currency: "ETB",
      },
      {
        id: "item-004-2",
        invoice_id: "inv-004",
        line_number: 2,
        description: "Sanitation Fee",
        quantity: null,
        unit: null,
        unit_price: null,
        amount: 500,
        discount_amount: 0,
        penalty_amount: 0,
        total_amount: 500,
        currency: "ETB",
      },
    ],
  },
  {
    id: "inv-005",
    invoice_number: "INV-2026-0005",
    assessment: {
      id: "asm-005",
      assessment_number: "ASM-2026-000061",
      assessment_date: "2026-08-03",
    },
    status: "ISSUED",
    currency: "ETB",
    subtotal: 14500,
    discount_amount: 500,
    penalty_amount: 0,
    total_amount: 14000,
    paid_amount: 0,
    balance_due: 14000,
    issued_at: "2026-08-05",
    due_date: "2026-09-05",
    paid_at: null,
    items: [
      {
        id: "item-005-1",
        invoice_id: "inv-005",
        line_number: 1,
        description: "Trade License Fee",
        quantity: null,
        unit: null,
        unit_price: null,
        amount: 6000,
        discount_amount: 500,
        penalty_amount: 0,
        total_amount: 5500,
        currency: "ETB",
      },
      {
        id: "item-005-2",
        invoice_id: "inv-005",
        line_number: 2,
        description: "Employee Levy",
        quantity: 12,
        unit: "PERSON",
        unit_price: 350,
        amount: 4200,
        discount_amount: 0,
        penalty_amount: 0,
        total_amount: 4200,
        currency: "ETB",
      },
      {
        id: "item-005-3",
        invoice_id: "inv-005",
        line_number: 3,
        description: "Warehouse Storage Fee",
        quantity: 300,
        unit: "M2",
        unit_price: 10,
        amount: 3000,
        discount_amount: 0,
        penalty_amount: 0,
        total_amount: 3000,
        currency: "ETB",
      },
      {
        id: "item-005-4",
        invoice_id: "inv-005",
        line_number: 4,
        description: "Signage Permit",
        quantity: null,
        unit: null,
        unit_price: null,
        amount: 1300,
        discount_amount: 0,
        penalty_amount: 0,
        total_amount: 1300,
        currency: "ETB",
      },
    ],
  },
  {
    id: "inv-006",
    invoice_number: "INV-2026-0006",
    assessment: null,
    status: "OVERDUE",
    currency: "ETB",
    subtotal: 3600,
    discount_amount: 0,
    penalty_amount: 180,
    total_amount: 3780,
    paid_amount: 0,
    balance_due: 3780,
    issued_at: "2026-07-15",
    due_date: "2026-08-10",
    paid_at: null,
    items: [
      {
        id: "item-006-1",
        invoice_id: "inv-006",
        line_number: 1,
        description: "Water Connection Fee",
        quantity: null,
        unit: null,
        unit_price: null,
        amount: 1500,
        discount_amount: 0,
        penalty_amount: 100,
        total_amount: 1600,
        currency: "ETB",
      },
      {
        id: "item-006-2",
        invoice_id: "inv-006",
        line_number: 2,
        description: "Electricity Meter Inspection",
        quantity: null,
        unit: null,
        unit_price: null,
        amount: 1200,
        discount_amount: 0,
        penalty_amount: 80,
        total_amount: 1280,
        currency: "ETB",
      },
      {
        id: "item-006-3",
        invoice_id: "inv-006",
        line_number: 3,
        description: "Drainage Maintenance Fee",
        quantity: null,
        unit: null,
        unit_price: null,
        amount: 900,
        discount_amount: 0,
        penalty_amount: 0,
        total_amount: 900,
        currency: "ETB",
      },
    ],
  },
];