
/*
|--------------------------------------------------------------------------
| Enums
|--------------------------------------------------------------------------
*/

export type TariffFormulaVariableSourceType =
  | "BASE_FIELD"
  | "CONSTANT";

export type TariffFormulaVariableDataType =
  | "NUMBER"
  | "DECIMAL"
  | "PERCENTAGE"
  | "MONEY";

/*
|--------------------------------------------------------------------------
| Base Field
|--------------------------------------------------------------------------
|
| Represents the BaseField returned when the API includes
| the `baseField` relationship.
|
*/

export interface TariffFormulaVariableBaseField {
  id: string;
  code: string;
  name?: string;
  label?: string;
  dataType?: string;
  measurementUnitId?: string | null;

  measurementUnit?: {
    id: string;
    code: string;
    name: string;
    symbol?: string | null;
  } | null;
}

/*
|--------------------------------------------------------------------------
| Tariff Formula Variable
|--------------------------------------------------------------------------
|
| Frontend/read model.
|
| `code` is generated by the backend and is therefore read-only
| from the frontend perspective.
|
*/

export interface TariffFormulaVariable {
  id: string;

  /*
  |--------------------------------------------------------------------------
  | Identity
  |--------------------------------------------------------------------------
  */

  code: string;

  variableName: string;

  label: string;

  /*
  |--------------------------------------------------------------------------
  | Source
  |--------------------------------------------------------------------------
  */

  sourceType: TariffFormulaVariableSourceType;

  baseFieldId: string | null;

  defaultValue: string | number | null;

  /*
  |--------------------------------------------------------------------------
  | Type
  |--------------------------------------------------------------------------
  */

  dataType: TariffFormulaVariableDataType;

  /*
  |--------------------------------------------------------------------------
  | Behaviour
  |--------------------------------------------------------------------------
  */

  isRequired: boolean;

  sortOrder: number;

  /*
  |--------------------------------------------------------------------------
  | Relationships
  |--------------------------------------------------------------------------
  */

  baseField?: TariffFormulaVariableBaseField | null;

  /*
  |--------------------------------------------------------------------------
  | System
  |--------------------------------------------------------------------------
  */

  createdAt?: string;

  updatedAt?: string;
}

/*
|--------------------------------------------------------------------------
| Create Request
|--------------------------------------------------------------------------
|
| Frontend request model.
|
| `code` is intentionally omitted because it is generated
| by the backend.
|
*/

export interface CreateTariffFormulaVariableRequest {
  variableName: string;

  label: string;

  sourceType: TariffFormulaVariableSourceType;

  baseFieldId?: string | null;

  defaultValue?: number | string | null;

  dataType: TariffFormulaVariableDataType;

  isRequired?: boolean;

  sortOrder?: number;
}

/*
|--------------------------------------------------------------------------
| Update Request
|--------------------------------------------------------------------------
|
| `code` is intentionally omitted.
|
| The backend-generated code is immutable after creation.
|
*/

export interface UpdateTariffFormulaVariableRequest {
  variableName?: string;

  label?: string;

  sourceType?: TariffFormulaVariableSourceType;

  baseFieldId?: string | null;

  defaultValue?: number | string | null;

  dataType?: TariffFormulaVariableDataType;

  isRequired?: boolean;

  sortOrder?: number;
}

/*
|--------------------------------------------------------------------------
| API Payload
|--------------------------------------------------------------------------
|
| Exact shape expected by Laravel.
|
| This type is useful at the API/service boundary.
|
*/

export interface TariffFormulaVariableApiPayload {
  variable_name: string;

  label: string;

  source_type: TariffFormulaVariableSourceType;

  base_field_id?: string | null;

  default_value?: number | string | null;

  data_type: TariffFormulaVariableDataType;

  is_required?: boolean;

  sort_order?: number;
}

